// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tauhatCppGS
double tauhatCppGS(NumericVector e, NumericVector s, NumericVector c, double h, int n);
RcppExport SEXP bigRfit_tauhatCppGS(SEXP eSEXP, SEXP sSEXP, SEXP cSEXP, SEXP hSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(tauhatCppGS(e, s, c, h, n));
    return __result;
END_RCPP
}
